name: Release

on:
  push:
    tags:
        - "v*.*.*"

jobs:
  main:
    name: Release process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.21
      GOLANGCI_LINT_VERSION: v1.55.2

    steps:

      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      # https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install tinygo
        uses: acifani/setup-tinygo@v2


      # https://golangci-lint.run/usage/install#other-ci
      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Check and get dependencies
        run: |
          go mod download
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: Build
        run: make

      - name: Build artifact
        uses: vimtor/action-zip@v1.1
        with:
          files: plugin.wasm .traefik.yml
          dest: plugin.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: plugin.zip